In [3]:
import pandas as pd


In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [6]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [1]:
records_count = len(df)

NameError: name 'df' is not defined

In [2]:
import pandas as pd


In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")


In [9]:
# Q2: Number of records (rows) in dataset
len(df)



9704

In [10]:
df["fuel_type"].nunique()

2

In [16]:
(df.isnull().sum() > 0).sum()


np.int64(4)

In [17]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(23.759122836520497)

In [18]:
median_before = df["horsepower"].median()

In [19]:
median_before

np.float64(149.0)

In [20]:
most_freq = df["horsepower"].mode()[0]

In [21]:
most_freq

np.float64(152.0)

In [22]:
df["horsepower"].fillna(most_freq, inplace=True)

/tmp/ipykernel_5152/3187842533.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["horsepower"].fillna(most_freq, inplace=True)


In [23]:
median_after = df["horsepower"].median()

In [24]:
median_after


np.float64(152.0)

In [25]:
median_before, median_after

(np.float64(149.0), np.float64(152.0))

In [26]:
import numpy as np

In [27]:
asia_cars = df[df["origin"] == "Asia"]

In [28]:
X = asia_cars[["vehicle_weight", "model_year"]].head(7).values

In [29]:
X


array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [30]:
XTX = X.T.dot(X)

In [31]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [32]:
XTX_inv = np.linalg.inv(XTX)

In [33]:
XTV_inv

NameError: name 'XTV_inv' is not defined

In [34]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [35]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [36]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [37]:
w = XTX_inv.dot(X.T).dot(y)

In [38]:
w

array([0.01386421, 0.5049067 ])

In [39]:
w.sum()

np.float64(0.5187709081074016)